import type { Metadata } from "next";
import ContextKingdom from "./context/ContextKingdom";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Inter, Poppins } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${inter.variable} ${poppins.variable} antialiased`}>
        <ContextKingdom>
          <section className="z-50">
            <Navbar />
          </section>
          {children}
          <section>
            <Footer />
          </section>
        </ContextKingdom>
      </body>
    </html>
  );
}
